---
- name: Configure NGINX as Reverse Proxy
  hosts: web
  become: yes

  tasks:
    - name: Ensure NGINX is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default NGINX configuration file
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload NGINX

    - name: Copy NGINX application configuration
      ansible.builtin.copy:
        src: nginx_app.conf
        dest: /etc/nginx/sites-available/yii2-app.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload NGINX

    - name: Enable NGINX application configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/yii2-app.conf
        dest: /etc/nginx/sites-enabled/yii2-app.conf
        state: link
      notify: Reload NGINX

  handlers:
    - name: Reload NGINX
      ansible.builtin.service:
        name: nginx
        state: reloaded
