---
- name: Deploy Yii2 Application as Docker Swarm Service
  hosts: web
  become: yes

  tasks:
    - name: Ensure /opt/docker_apps directory exists
      ansible.builtin.file:
        path: /opt/docker_apps
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml to remote host
      ansible.builtin.copy:
        src: ../yii2-app/docker-compose.yml # Path to your docker-compose.yml in yii2-app dir
        dest: /opt/docker_apps/docker-compose.yml
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Docker Swarm stack
      community.docker.docker_stack:
        state: present
        name: yii2-app-stack # Name of your Docker Swarm stack
        compose:
          - /opt/docker_apps/docker-compose.yml
